typography_spectrum: 0.7911479729227722
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.9621034795418382
  saturation: 0.5609141341410577
  rhythmicContrast: 0.8330813799984753
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Basilico
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: We bas!
purpose: []
